# Generated by Django 3.1 on 2020-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
