# Generated by Django 3.1 on 2020-09-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_create_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='id',
            new_name='s_id',
        ),
    ]
