# Generated by Django 3.1 on 2020-09-03 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200903_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
